# Worksheet- 0

**Group:** LC6G16

**Name:** Riya Prajapati

**Student ID:** 2329456

# 4.1 Exercise on Functions

## Create a Python program that converts between different units of measurement.

In [ ]:
def conversion():
    """
    A simple unit conversion program that allows the user to convert:
    - Length: meters to feet, feet to meters
    - Weight: kilograms to pounds, pounds to kilograms
    - Volume: liters to gallons, gallons to liters

    The function prompts the user for the type of conversion, takes input,
    and displays the converted value.
    """
    print("Choose the type of conversion:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    choose = input("Enter length, weight, or volume: ").strip().lower()  #to Handle Input Variations like LENGTH OR length

    try:
        if choose == "length":
            value = float(input("Enter the value: "))
            meters_to_feet = value * 3.28084
            feet_to_meters = value * 0.3048
            print(f"{value} meters is {meters_to_feet:.2f} feet")
            print(f"{value} feet is {feet_to_meters:.2f} meters")

        elif choose == "weight":
            value = float(input("Enter the value: "))
            kg_to_pounds = value * 2.20462
            pounds_to_kg = value * 0.453592
            print(f"{value} kg is {kg_to_pounds:.2f} lbs")
            print(f"{value} lbs is {pounds_to_kg:.2f} kg")

        elif choose == "volume":
            value = float(input("Enter the value: "))
            liters_to_gallons = value * 0.264172
            gallons_to_liters = value * 3.78541
            print(f"{value} liters is {liters_to_gallons:.2f} gallons")
            print(f"{value} gallons is {gallons_to_liters:.2f} liters")

        else:
            print("Invalid choice. Please enter length, weight, or volume.")

    except ValueError:
        print("Invalid input! Please enter a numeric value.")

# Run the function
conversion()


Choose the type of conversion:
1. Length
2. Weight
3. Volume
Enter length, weight, or volume: volume
Enter the value: 20
20.0 liters is 5.28 gallons
20.0 gallons is 75.71 liters


## Create a Python program that performs various mathematical operations on list of numbers.

In [ ]:
def sum_list(numbers):
    """Calculate the sum of a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The sum of the numbers.
    """
    return sum(numbers)

def average_list(numbers):
    """Calculate the average of a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)

def maximum_list(numbers):
    """Find the maximum value in a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The maximum value in the list.
    """
    return max(numbers)

def minimum_list(numbers):
    """Find the minimum value in a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The minimum value in the list.
    """
    return min(numbers)

def main():
    # Display operation menu
    print("Select an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    # Get operation choice
    choice = input("\nEnter your choice (1-4): ").strip()

    # Validate operation choice
    if choice not in ['1', '2', '3', '4']:
        print("\nError: Invalid operation selection.")
        return

    # Get numbers input
    try:
        nums_input = input("\nEnter numbers separated by spaces: ")
        num_strings = nums_input.split()

        if not num_strings:
            raise ValueError("Empty list")

        numbers = [float(num) for num in num_strings]

    except ValueError as e:
        if str(e) == "Empty list":
            print("\nError: No numbers entered.")
        else:
            print("\nError: Non-numeric value detected.")
        return

    # Perform selected operation
    try:
        if choice == '1':
            result = sum_list(numbers)
        elif choice == '2':
            result = average_list(numbers)
        elif choice == '3':
            result = maximum_list(numbers)
        elif choice == '4':
            result = minimum_list(numbers)

        # Display result with formatting
        print(f"\nResult: {result:.2f}")  # Rounded to 2 decimal places

    except ZeroDivisionError:
        print("\nError: Cannot calculate average of an empty list.")
    except Exception as e:
        print(f"\nAn unexpected error occurred: {e}")

main()

Select an operation:
1. Sum
2. Average
3. Maximum
4. Minimum

Enter your choice (1-4): 1

Enter numbers separated by spaces: 10 20 30 40 50

Result: 150.00


# 4.2 Exercise on List Manipulation

## 1. Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(lst):

  return lst[::2]
# Get user input, split it, and convert to integers
user_input = list(map(int, input("Enter numbers separated by space: ").split()))

print("Original list:", user_input)

new_list = extract_every_other(user_input)
print("New list: ", new_list)




Enter numbers separated by space: 1 2 3 4 5 6 
Original list: [1, 2, 3, 4, 5, 6]
New list:  [6, 4, 2]


## 2.  Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end + 1]  # Slicing from start to end (inclusive)

# Example usage
input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4

print("Original list:", input_list)
sub_list = get_sublist(input_list, start_index, end_index)
print("Sublist:", sub_list)

Original list: [1, 2, 3, 4, 5, 6]
Sublist: [3, 4, 5]


## 3. Write a Python function that reverses a list using slicing.

In [ ]:
def reverse_list(lst):
   return lst[::-1]
input_list = [1, 2, 3, 4, 5]
print("Original list:", input_list)
reverseList = reverse_list(input_list)
print("Reverse list: ",reverseList)


Original list: [1, 2, 3, 4, 5]
Reverse list:  [5, 4, 3, 2, 1]


## 4.  Remove the First and Last Elements





In [ ]:
def remove_first_last(lst):
    return lst[1:-1]  # Slicing to exclude the first and last elements

# Example usage
input_list = [1, 2, 3, 4, 5]
print("Original List:", input_list)
output_list = remove_first_last(input_list)
print("Output List:", output_list)

Original List: [1, 2, 3, 4, 5]
Output List: [2, 3, 4]


## 5. Write a Python function that extracts the first n elements from a list.

In [ ]:
def get_first_n(lst, n):
  return lst[:n]

input_list = [1, 2, 3, 4, 5, 6]
n = 3
print("Original list:", input_list)
Output = get_first_n(input_list, n)
print("First Element list:", Output)

Original list: [1, 2, 3, 4, 5, 6]
Result: [1, 2, 3]


## 6. Write a Python function that extracts the last n elements of a list using slicing.

In [ ]:
def get_last_n(lst, n):
  return lst[-n:]

input_list = [1,2,3,4,5]
n = 2
print("Original list:",input_list)
Output = get_last_n(input_list,n)
print("Last Element list: ",Output)

Original list: [1, 2, 3, 4, 5]
Last Element list:  [4, 5]


## 7. Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

In [ ]:
def reverse_skip(lst):
  return lst[-2::-2]

input_list = [1,2,3,4,5,6]

print("Original list:", input_list)

new_list = reverse_skip(input_list)
print("Reverse skip list: ", new_list)

Original list: [1, 2, 3, 4, 5, 6]
Reverse skip list:  [5, 3, 1]


# 4.3 Exercise on Nested List

## 1. Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

In [ ]:
def flatten(lst):
    return [num for sublist in lst for num in sublist]  # Flatten the nested list

input_list = [[1, 2], [3, 4], [5]]
print("Original list:", input_list)

output_list = flatten(input_list)
print("Flattened list:", output_list)

Original list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


## 2. Write a Python function that extracts a specific element from a nested list given its indices.





In [ ]:
def access_nested_element(lst, indices):
    element = lst  # Start with the original list
    for index in indices:  # Iterate through the indices
        element = element[index]  # Access the next level of the nested list
    return element  # Return the final accessed element

# Example usage
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]  # This should access lst[1][2], which is 6
print("Original list:", lst)

output_element = access_nested_element(lst, indices)
print("Accessed element:", output_element)

Original list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Accessed element: 6


## 3. Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [ ]:
def sum_nested(lst):
    s = 0
    for i in lst:
        if isinstance(i, list):
            s += sum_nested(i)  # Recursively sum the nested list
        else:
            s += i
    return s

# Example usage
input_list = [[1, 2], [3, [4, 5]], 6]
output_element = sum_nested(input_list)
print("Sum of all elements:", output_element)

Sum of all elements: 21


## 4. Write a Python function that removes all occurrences of a specific element from a nested list.

In [ ]:
def remove_element(lst, elem):
    # Iterate through each sublist in the list
    for sublist in lst:
        # Remove all occurrences of elem in the sublist
        while elem in sublist:
            sublist.remove(elem)
    return lst

# Example usage
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

print("Original list:", lst)
output = remove_element(lst, elem)
print("Modified list:", output)

Original list: [[1, 2], [3, 2], [4, 5]]
Modified list: [[1], [3], [4, 5]]


## 5. Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [ ]:
def find_max(lst):
    max_value = float('-inf')  # Start with the smallest possible value

    for i in lst:
        if isinstance(i, list):  # If the element is a list, recurse
            max_value = max(max_value, find_max(i))
        else:
            max_value = max(max_value, i)  # Update max_value if the element is greater

    return max_value

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
print("Original list:", nested_list)
print("Maximum element:", find_max(nested_list))


Original list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


## 6. Write a Python function that counts how many times a specific element appears in a nested list.

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):  # If item is a list, recursively count occurrences
            count += count_occurrences(item, elem)
        elif item == elem:  # If item is the element we are looking for, increase count
            count += 1
    return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

print("Original list:", lst)
output = count_occurrences(lst, elem)
print("The count of number:", output)


Original list: [[1, 2], [2, 3], [2, 4]]
The count of number: 3


## 7. Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [ ]:
def deep_flatten(lst):
    single_list = []  # Create a new list inside the function to avoid global state issues

    def flatten(elements):
        for element in elements:
            if isinstance(element, list):
                flatten(element)  # Recursively flatten nested lists
            else:
                single_list.append(element)  # Append non-list elements

    flatten(lst)
    return single_list

# Test input
input_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print("Original list:", input_list)
output = deep_flatten(input_list)
print("A single flattened list:", output)


Original list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
A single flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


## 8. Write a Python function that calculates the average of all elements in a nested list.

In [ ]:
def average_nested(lst):
    def flatten(nested):
        flat_list = []
        for item in nested:
            if isinstance(item, list):
                flat_list.extend(flatten(item))
            else:
                flat_list.append(item)
        return flat_list

    flat_numbers = flatten(lst)  # Extract all numbers from nested lists
    return sum(flat_numbers) / len(flat_numbers) if flat_numbers else 0

nested_list = [[1, 2], [3, 4], [5 , 6]]
print("Original list:", nested_list)
output = average_nested(nested_list)
print("Average number:", output)


Original list: [[1, 2], [3, 4], [5, 6]]
Average number: 3.5


# 10.1 Basic Vector and Matrix Operation with Numpy.

## Problem - 1: Array Creation

### 1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

# Initialize an empty 2x2 array
array_2d = np.empty((2, 2))

# Print the array
print(array_2d)


[[3.1610884e-316 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]


### 2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np

# Create a 4x2 array of ones
one_array = np.ones((4, 2))

# Print the array
print(one_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

# Create a 4x5 array filled with 111, with integer type
arr = np.full((4, 5), fill_value=111, dtype=int)

# Display the array
print("Array:\n", arr)

# Get and display the datatype of the array
print("Array datatype:", arr.dtype)

# Get and display the dimensions of the array
print("Array Dimensions:", arr.ndim)

# Get and display the shape of the array
print("Array Shape:", arr.shape)

# Get and display the total number of elements in the array
print("Total Elements in the Array:", arr.size)


Array:
 [[111 111 111 111 111]
 [111 111 111 111 111]
 [111 111 111 111 111]
 [111 111 111 111 111]]
Array datatype: int64
Array Dimensions: 2
Array Shape: (4, 5)
Total Elements in the Array: 20


### 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np

# Define an existing array
given_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a new array of zeros with the same shape and type as the given array
arr = np.zeros_like(given_array)

# Display the array
print("Array:\n", arr)

# Get and display the datatype of the array
print("Array datatype:", arr.dtype)

# Get and display the dimensions of the array
print("Array Dimensions:", arr.ndim)

# Get and display the shape of the array
print("Array Shape:", arr.shape)

# Get and display the total number of elements in the array
print("Total Elements in the Array:", arr.size)


Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Array datatype: int64
Array Dimensions: 2
Array Shape: (3, 3)
Total Elements in the Array: 9


### 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np

# Define an existing array
given_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a new array of ones with the same shape and type as the given array
arr = np.ones_like(given_array)

# Display the array
print("Array:\n", arr)

# Get and display the datatype of the array
print("Array datatype:", arr.dtype)

# Get and display the dimensions of the array
print("Array Dimensions:", arr.ndim)

# Get and display the shape of the array
print("Array Shape:", arr.shape)

# Get and display the total number of elements in the array
print("Total Elements in the Array:", arr.size)


Array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Array datatype: int64
Array Dimensions: 2
Array Shape: (3, 3)
Total Elements in the Array: 9


### 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

new_list = [1, 2, 3, 4]

# Convert the list to a NumPy array
arr = np.array(new_list)

print("Numpy Array: ",arr)

Numpy Array:  [1 2 3 4]


## Problem - 2: Array Manipulation: Numerical Ranges and Array indexing

### 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating an array from 10 to 49 using arange
x = np.arange(10, 50) # 50 is the stop value, which is excluded

# Printing the array from 10 to 49
print("Array from 10 to 49:")
print(x)


Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}

In [ ]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a 3x3 matrix with values ranging from 0 to 8
x = np.arange(9).reshape(3, 3)

# Printing a message indicating a 3x3 matrix
print('3x3 matrix:')

# Printing the resulting 3x3 matrix 'x'
print(x)


3x3 matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
# Importing the NumPy library with an alias 'np'
import numpy as np

identity_matrix = np.eye(3)

# Printing a message indicating a 3x3 matrix
print('3x3 identity matrix:')

print(identity_matrix)

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 5. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np  # Import numpy as np

x = np.random.random(30)  # Create a random array of size 30
y = x.mean()  # Find the mean of the array

print(x)  # Print the array
print(y)  # Print the mean value


[6.97290120e-01 8.21237418e-02 2.77552875e-01 1.67051031e-01
 5.63573406e-01 1.54898388e-01 3.50568634e-02 5.77132399e-01
 5.45015202e-01 5.03113786e-01 1.75012253e-01 8.79959324e-02
 9.95691769e-01 3.75621779e-01 2.69901642e-01 6.28932762e-01
 9.44968788e-01 9.52347092e-01 7.29435298e-01 1.94054676e-01
 3.47669260e-01 3.45621108e-01 8.55812873e-01 2.53757968e-01
 4.78692408e-01 4.52122357e-01 3.48517185e-01 8.79089316e-01
 4.36656604e-01 2.68903780e-04]
0.4451659262574019


### 6. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
# importing numpy library
import numpy as np

# creating numpy array
arr = np.random.random((10,10))

# finding minimum value of an array
min_val = np.amin(arr)

# finding maximum value of an array
max_val = np.amax(arr)

# printing values
print("10x10 array:\n",arr)
print("Minimum Value:\n",min_val)
print("Maximum Value:\n",max_val)

10x10 array:
 [[0.35978938 0.9246664  0.74562211 0.65601409 0.47770443 0.59003462
  0.26528251 0.64785994 0.18810346 0.41354717]
 [0.13373349 0.1506474  0.4139776  0.70407649 0.18075389 0.97333739
  0.84140011 0.68787862 0.09030791 0.15805267]
 [0.63376478 0.31474659 0.54372008 0.02695311 0.72170595 0.55162915
  0.13353351 0.82208835 0.19398282 0.93600724]
 [0.07826575 0.26967345 0.07893399 0.24443846 0.08849485 0.27805835
  0.27244073 0.80618861 0.02579852 0.0834442 ]
 [0.58087981 0.99767261 0.80014353 0.97744647 0.31471289 0.13726012
  0.80593407 0.3327009  0.74315712 0.9905098 ]
 [0.51933528 0.85436089 0.61327974 0.39882796 0.56084236 0.76040211
  0.21079635 0.1172837  0.12052192 0.86391247]
 [0.19738056 0.47506481 0.16602911 0.09674118 0.4539418  0.54435861
  0.06144753 0.14987079 0.05187105 0.24965641]
 [0.64504681 0.64971771 0.65811765 0.43931123 0.09604248 0.4742803
  0.75443963 0.92815463 0.26721442 0.90640561]
 [0.62594035 0.67631312 0.52814263 0.4665106  0.40063137 0.9077268


### 7. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating an arr of 10 zeros using np.zeros()
arr = np.zeros(10)
arr[5] = 1

# Printing a message indicating an arr of 10 zeros
print("An arr of 10 zeros:")

# Printing the arr of 10 zeros
print(arr)

An arr of 10 zeros:
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


### 8. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
# Importing the NumPy library with an alias 'np'
import numpy as np

arr =  [1,2,0,0,4,0]
print("Orginal Array:",arr)

# using shortcut method to reverse
res = np.flip(arr)

# printing result
print("Reverse array:",res)


Orginal Array: [1, 2, 0, 0, 4, 0]
Reverse array: [0 4 0 0 2 1]


### 9. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np
arr = np.ones((5,5))
print("2D Array:\n",arr)
arr[1:-1, 1:-1] = 0
print("1 Border and 0 inside:\n",arr)

2D Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 Border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# Creating an 8x8 matrix filled with zeros
x = np.zeros((8, 8), dtype=int)

# Filling the checkerboard pattern
x[1::2, ::2] = 1  # Set alternate elements starting from row 1
x[::2, 1::2] = 1  # Set alternate elements starting from row 0

# Printing the resulting checkerboard pattern
print("Checkerboard pattern:")
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Problem - 3: Array Operations:

### 1. Add the two array.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
result = x + y

print("Add the two array:\n",result)

Add the two array:
 [[ 6  8]
 [10 13]]


### 2. Subtract the two array.

In [ ]:
import numpy as np
x = np.array([[5,6],[7,8]])
y = np.array([[1,2],[3,5]])
result = x - y

print("Subtract the two array:\n",result)

Subtract the two array:
 [[4 4]
 [4 3]]


### 3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# perform element-wise multiplication between array1 and array2
result = np.multiply(array1, array2)

print(" Multiply the array:\n",result)


 Multiply the array:
 [ 4 10 18]


### 4. Find the square of each element of the array.

In [ ]:
import numpy as np

array1 = np.array([2, 4, 5, 6])

# compute square root of each element in array1
result = np.square(array1)

print("Square Number:\n",result)

Square Number:
 [ 4 16 25 36]


### 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np

# Defining vectors
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
x = np.array([7, 8, 9])
y = np.array([10, 11, 12])

# Dot product calculations
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y

# Printing results
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:", dot_xv)
print("Dot product of x and y:", dot_xy)


Dot product of v and w: 32
Dot product of x and v: 50
Dot product of x and y: 266


### 6. Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

x = np.array((0, 1))
y = np.array((2, 1))
v = np.array((-1, -1))
w = np.array((4, -8))

# Stacking x and y along rows
arr = np.vstack((x, y))  # Correct for concatenating x and y along rows
print("Stacking x and y along rows:\n", arr)

# Concatenating v and w along columns
arr2 = np.column_stack((v, w))  # Correct for concatenating v and w along columns
print("Concatenating v and w along columns:\n ", arr2)


Stacking x and y along rows:
 [[0 1]
 [2 1]]
Concatenating v and w along columns:
 [[-1  4]
 [-1 -8]]


### 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([1, 2, 3])
v = np.array([4, 5, 6])

result = np.concatenate((x, v))
print(result)

[1 2 3 4 5 6]


### Common Errors in NumPy Concatenation

1. **TypeError**: If `x` or `v` are not NumPy arrays, you'll get a `TypeError`. Convert them to NumPy arrays first.
2. **ValueError**: If `x` and `v` have different dimensions (e.g., one is 1D and the other is 2D), you'll get a `ValueError`. Ensure they have the same shape along the concatenation axis.

#### Example of TypeError:

x = [1, 2, 3]  # Not a NumPy array
v = np.array([4, 5, 6])

result = np.concatenate((x, v))  # TypeError

# Problem - 4: Matrix Operations:

## For the following arrays

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:

### 1. Prove A.A−1 = I.

In [ ]:
import numpy as np

# Define matrix A
A = np.array([[3, 4], [7, 8]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with its inverse
result = np.dot(A, A_inv)

# Print result
print("A * A_inv:\n", result)

# Check if result is an identity matrix
I = np.eye(2)  # 2x2 identity matrix
print("Is A * A_inv equal to I? ", np.allclose(result, I))


A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A_inv equal to I?  True


### 2. Prove AB ̸= BA.

In [ ]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute AB
AB = np.dot(A, B)

# Compute BA
BA = np.dot(B, A)

# Print results
print("AB:\n", AB)
print("BA:\n", BA)

# Check if AB is not equal to BA
print("Is AB not equal to BA? ", not np.array_equal(AB, BA))


AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB not equal to BA?  True


### 3. Prove (AB)T = BTAT

In [ ]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute AB
AB = np.dot(A, B)

# Compute (AB)^T
AB_T = AB.T

# Compute B^T and A^T
B_T = B.T
A_T = A.T

# Compute B^T * A^T
BT_AT = np.dot(B_T, A_T)

# Print results
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)

# Check if (AB)^T == B^T * A^T
print("Is (AB)^T equal to B^T * A^T? ", np.array_equal(AB_T, BT_AT))


(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T?  True


## Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [ ]:
import numpy as np

# Define matrix A
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

# Define matrix B
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using X = A_inv * B
X = np.dot(A_inv, B)

# Print results
print("Solution for x, y, z = ",X)



Solution for x, y, z =  [ 2.  1. -2.]
